config/routes.rb
Rails.application.routes.draw do
  get 'nice_books/all', to: 'books#index', as: :all_books, defaults: { format: :json }

  get 'authors/new_author', to: 'authors#new', as: :new_author, defaults: { format: :html }
  post 'authors/create', defaults: { format: :html }
  get 'authors/:last_name', to: 'authors#show', as: :author_name, defaults: { format: :html }

  root to: 'authors#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :integer          not null, primary key
#  first_name :string           not null
#  last_name  :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Author < ApplicationRecord
  has_many :books, class_name: 'Book', foreign_key: :author_id
  string = /\A[a-zA-Z\s]+\z/
  validates :first_name, presence: true, format: { with: string }
  validates :last_name, presence: true, format: { with: string }
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  short_name :string
#  full_name  :string
#  year       :date
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ApplicationRecord
  before_save :set_short_name

  belongs_to :author, class_name: 'Author', foreign_key: :author_id

  def set_short_name
    self.short_name = full_name.parameterize.underscore
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def show
    @author = Author.find(params[:last_name])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to author_name_url(@author), notice: 'new_author_has_been_created'
    else
      render :new
    end
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/new.html.haml
= form_for(@author,url: authors_create_path, html: { class: 'form-group', role: 'form' }) do |f|
  - if @author.errors.any?
    #error_explanation
      .alert.alert-danger                                                                                                    
        %ul
          - @author.errors.full_messages.each do |msg|
            %li= msg

  .form-group
    = f.label :first_name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :first_name, class: 'form-control'
  .form-group
    = f.label :last_name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :last_name, class: 'form-control '
  .form-actions
    = f.submit class: 'btn btn-primary'
    = link_to all_books_path, class: 'btn btn-cancel' do
      All books

app/views/authors/show.html.haml
%br

%dl.dl-horizontal
  %dt Author first name
  %dd= @author.first_name
  %dt Author last name
  %dd= @author.last_name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>